### ISSUE TITLE
Feature request! Support new CSS blocks...

### ISSUE THREAD

**Issue by a-h** [Joe-Davidson1802/templ.vim#1]
Hey there, I've updated https://github.com/a-h/templ-vscode to include support for the new CSS blocks.

It went from this:

<img width="950" alt="Screen Shot 2021-06-24 at 20 18 14" src="https://user-images.githubusercontent.com/1029947/123328217-3b4ecb00-d533-11eb-9145-f840d85fb6ea.png">

To this. Note how the expression attribute values are formatted correctly now `{%= "attribute_value" %}` in addition to the new CSS blocks.

<img width="952" alt="Screen Shot 2021-06-24 at 20 18 39" src="https://user-images.githubusercontent.com/1029947/123328216-3ab63480-d533-11eb-945e-0cbfa40a2efe.png">

There's a TextMate grammar in the templ-vscode repo, but I couldn't find a way to convert it for use in vim. I did it over a series of commits, so it should make sense if you read through.

**Comment by joerdav** [comment]
Fixed this in 2d1ca014c360a46aade54fc9b94f065f1deb501a
